### ISSUE TITLE
ECU Schematic Comments (Commit 74a4f86)

### ISSUE THREAD

**Issue by DanielHeEGG** [UCI-Rocket-Project/rocket2-ecu-hardware#1]
This review references commit 74a4f86f4d4766634681fad2ede5eb32b94be026

This is a high level review only. I did not check specific details (component value selection, orientation, footprint, label names, etc.) The design engineer is ultimately responsible for them.

## Solenoid, PT, TC
- Ok if designs are identical to current GSE designs, did not give detailed review

## REDS / Power
- Do we draw enough current to warrant a switching reg for 3V3?
- Recommend use both power sources for Insta360 charging
- USB-C port for Insta360 charging, 5V only no PD
- Assuming power switching related circuits have already been tested. **Please make sure the orientations are correct**

## Inertial Sensors
- Recommend moving away from Bosch sensors entirely (@RobertAWoo714 thoughts?)

## ECU Radios
- Why do we have 2 radios for ECU?

## GPS
- Recommend leaving nRST floating or open drain, or microcontroller will pull low and hard reset every time
- Recommend external crystal clock and backup battery
- RF shield not necessary, but ok
- **GPS_TX ISNT EVEN CONNECTED WTF**

**Comment by Dat-Bois** [comment]
## Reds:
 - We draw an estimated peak ~300ma (the radio is most of it). Issue is mostly that any LDO kills itself due to thermals. I tested over Summer with a few different ones and even though its within spec, they can't operate for long enough and I no longer trust them. 
 - I disagree with this since once GSE charges the battery past 24V the load will be put on the charging circuit which it is not rated for (Insta360 draws 5V/3A). What I am willing to do is once GSE is disconnected it can switch to battery power via mosfet, but I don't want in parallel.
 - I did USB-A for this so no one thinks they can plug their laptop or device in and since we don't have any PD negotiation it may not be safe. Also won't the insta360 try to negotiate power from PD if we do USB-C? Idk how that stuff works.
 - Yeah fixed this last time when we found the mosfet issue

## Inertial Sensors:
 - Ill wait for Robert's input on this

## ECU Radios:
 - We discussed this earlier that the ECU will have two separate 915mhz radios (Ryan will have more input on this). 
 - REDs will have a single 433mhz

## GPS:
 - Will fix ✅ 
 - Sure, but will this even help for our usecase (once Rocket is on it stays on pretty much)
 - Shield looks cool hehehaha
 - Will fix ✅

**Comment by DanielHeEGG** [comment]
## REDS
* ok
* ok use only ground power
* Use USB-C, PD negotiation is optional, 5V is default
* ok

## ECU Radios
* ok
* ok

## GPS
* ok
* Fine we don't need to bother
* fine
* ok

**Comment by cadguyen** [comment]
From what I can see, **optocouplers** aren't going to be used to measure cell condition. Out of curiosity, what were your results from testing them?

**Comment by RobertAWoo714** [comment]
## Intertial Sensors:
I got the Bosch sensors in a pretty useful circumstance where I don't see an issue coming that I haven't dealt with already. I'd keep them since we already wrote the drivers for them.

## LEDS
Recommend adding an LED for memory and GPS each. Easiest way to troubleshoot/see if these sensors are working is to blink an LED whenever each component is done with a function.

## PTs and TCs
Lets add 2 extra PTs and 1 extra TC line just for any potential major fuck ups during VTF or coldflows. We already had a problem with the TC's SPI line getting confused during a cold flow, so lets try to be prepared for that.

other than that, I agree with everything you 2 have been saying so far
